// <auto-generated />
using System;
using System.Text.Json;
using Conductor.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conductor.Infrastructure.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    [Migration("20241005125046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conductor.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("deployment_id");

                    b.ToTable("deployment", "public");
                });

            modelBuilder.Entity("Conductor.Domain.Numbers.Number", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("number_id");

                    b.ToTable("number", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("105493e5-9d9b-46eb-be31-a3906514bf2e"),
                            Kind = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("9d7f4492-3bde-4dc7-805d-31c3ab0448e6"),
                            Kind = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("53b9986a-b2c6-4e7e-9ea1-ac02ba315154"),
                            Kind = 3,
                            Value = 1
                        });
                });

            modelBuilder.Entity("Conductor.Domain.Processes.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("process_id");

                    b.ToTable("process", "public");
                });

            modelBuilder.Entity("Conductor.Domain.Deployments.Deployment", b =>
                {
                    b.OwnsMany("Conductor.Domain.Deployments.DeploymentTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("BufferSize")
                                .HasColumnType("integer")
                                .HasColumnName("buffer_size");

                            b1.Property<Guid>("DeploymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("deployment_id");

                            b1.Property<int>("ParallelCount")
                                .HasColumnType("integer")
                                .HasColumnName("parallel_count");

                            b1.Property<Guid>("ProcessId")
                                .HasColumnType("uuid")
                                .HasColumnName("process_id");

                            b1.Property<Guid>("RevisionId")
                                .HasColumnType("uuid")
                                .HasColumnName("revision_id");

                            b1.HasKey("Id")
                                .HasName("target_id");

                            b1.HasIndex("DeploymentId");

                            b1.ToTable("target", "public");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Conductor.Domain.Processes.Process", b =>
                {
                    b.OwnsMany("Conductor.Domain.Processes.Revision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<JsonElement>("Content")
                                .HasColumnType("jsonb")
                                .HasColumnName("content");

                            b1.Property<Instant>("Created")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created");

                            b1.Property<bool>("IsDraft")
                                .HasColumnType("boolean")
                                .HasColumnName("is_draft");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.Property<Guid>("ProcessId")
                                .HasColumnType("uuid")
                                .HasColumnName("process_id");

                            b1.Property<string>("ReleaseNotes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("release_notes");

                            b1.HasKey("Id")
                                .HasName("revision_id");

                            b1.HasIndex("ProcessId");

                            b1.ToTable("revision", "public");

                            b1.WithOwner()
                                .HasForeignKey("ProcessId");
                        });

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
